#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        # The -d tells your app to daemonize
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        # Sends SIGTERM for graceful exit and file cleanup
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
